'use client';

import { ResponsiveLine } from '@nivo/line';

type chartProps = {
	averages: number[];
};

const AvgChart = ({ averages }: chartProps) => {
	//weird hack to stop annoying warnings in console generated by nivo chart
	const error = console.error;
	console.error = (...args: any) => {
		if (/defaultProps/.test(args[0])) return;
		error(...args);
	};

    let data = [];
    for (let i = 0; i < 10; i++) {
        data[i] = {
            x: i + 1,
            y: averages.length > i ? averages[i] : 0
        }
    }

	const chartData = [
		{
			id: 1,
			data: data.reverse()
		}
	];

    console.log(chartData);

	return (
		<div className="h-80 w-screen sm:w-1/2">
			<ResponsiveLine
				colors="yellow"
				theme={{
					axis: {
						ticks: {
							text: {
								fontSize: 14,
								fill: 'yellow'
							}
						}
					}
				}}
				data={chartData}
				margin={{ top: 20, right: 50, bottom: 70, left: 50 }}
				xScale={{ type: 'point' }}
				yScale={{
					type: 'linear',
					min: 0,
					max: 'auto'
				}}
				axisBottom={{
					tickPadding: 5,
					tickRotation: 0
				}}
				lineWidth={4}
				pointSize={12}
				pointBorderWidth={2}
				pointLabelYOffset={-12}
				useMesh={true}
			/>
		</div>
	);
};

export default AvgChart;
