import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { NavBar } from './_components/NavBar';
import SessionProvider from '@/providers/SessionProvider';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<SessionProvider>
					<div className="flex flex-col">
						<NavBar />
						<div className="bg-slate-900 min-h-screen">{children}</div>
					</div>
				</SessionProvider>
				<Toaster />
			</body>
		</html>
	);
}
